#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CommunityCenter.Resource", IsApplication=true)]

namespace CommunityCenter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int bottom_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bottom_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fade_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fade_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int loading_round = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_in_from_bottom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_in_from_top = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_out_to_bottom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int slide_out_to_top = 2130968584;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010026
			public const int civ_border_color = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int civ_border_overlay = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int civ_border_width = 2130772005;
			
			// aapt resource value: 0x7f010028
			public const int civ_fill_color = 2130772008;
			
			// aapt resource value: 0x7f010022
			public const int ptrAdapterViewBackground = 2130772002;
			
			// aapt resource value: 0x7f01000c
			public const int ptrAnimationStyle = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ptrDrawable = 2130771974;
			
			// aapt resource value: 0x7f010024
			public const int ptrDrawableBottom = 2130772004;
			
			// aapt resource value: 0x7f010008
			public const int ptrDrawableEnd = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ptrDrawableStart = 2130771975;
			
			// aapt resource value: 0x7f010023
			public const int ptrDrawableTop = 2130772003;
			
			// aapt resource value: 0x7f010013
			public const int ptrFriction = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int ptrGoogleProgressStyle = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ptrGoogleViewStyle = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int ptrHeaderBackground = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int ptrHeaderSubTextColor = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int ptrHeaderTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int ptrHeaderTextColor = 2130771970;
			
			// aapt resource value: 0x7f01001e
			public const int ptrHideRefeshableViewWhileRefreshingDuration = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int ptrHideRefeshableViewWhileRefreshingEnabled = 2130771995;
			
			// aapt resource value: 0x7f01000d
			public const int ptrIndicatorStyle = 2130771981;
			
			// aapt resource value: 0x7f010017
			public const int ptrListViewExtrasEnabled = 2130771991;
			
			// aapt resource value: 0x7f010004
			public const int ptrMode = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int ptrOverScroll = 2130771977;
			
			// aapt resource value: 0x7f010010
			public const int ptrPullLabel = 2130771984;
			
			// aapt resource value: 0x7f010021
			public const int ptrRefeshableViewProgressBarOnCenterHeight = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int ptrRefeshableViewProgressBarOnCenterWidth = 2130772000;
			
			// aapt resource value: 0x7f010011
			public const int ptrRefreshLabel = 2130771985;
			
			// aapt resource value: 0x7f010000
			public const int ptrRefreshableViewBackground = 2130771968;
			
			// aapt resource value: 0x7f010012
			public const int ptrReleaseLabel = 2130771986;
			
			// aapt resource value: 0x7f010018
			public const int ptrRotateDrawableWhilePulling = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int ptrScrollingWhileRefreshingEnabled = 2130771990;
			
			// aapt resource value: 0x7f010019
			public const int ptrSetGoogleViewLayoutSizeToActionbarHeight = 2130771993;
			
			// aapt resource value: 0x7f01001d
			public const int ptrShowGoogleStyleViewAnimationDuration = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int ptrShowGoogleStyleViewAnimationEnabled = 2130771994;
			
			// aapt resource value: 0x7f010005
			public const int ptrShowIndicator = 2130771973;
			
			// aapt resource value: 0x7f010014
			public const int ptrSmoothScrollDuration = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int ptrSmoothScrollLongDuration = 2130771989;
			
			// aapt resource value: 0x7f01000b
			public const int ptrSubHeaderTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f01001f
			public const int ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingDuration = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingEnabled = 2130771996;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f09000a
			public const int bg_gray = 2131296266;
			
			// aapt resource value: 0x7f090013
			public const int bg_lightgray = 2131296275;
			
			// aapt resource value: 0x7f090005
			public const int black = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int blue = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int color_nomal = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int color_pressed = 2131296258;
			
			// aapt resource value: 0x7f090011
			public const int commo_text_color = 2131296273;
			
			// aapt resource value: 0x7f090006
			public const int darkblue = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int darkgray = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int editgray = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int griditems_bg = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int halftransparent = 2131296268;
			
			// aapt resource value: 0x7f090008
			public const int ingray = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int light_orange = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int lightgray = 2131296265;
			
			// aapt resource value: 0x7f090012
			public const int line = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int pink = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int red = 2131296256;
			
			// aapt resource value: 0x7f09000d
			public const int transparent = 2131296269;
			
			// aapt resource value: 0x7f090003
			public const int white = 2131296259;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int header_footer_left_right_padding = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int header_footer_top_bottom_padding = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int header_pull_to_refresh_image_padding = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int indicator_corner_radius = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int indicator_internal_padding = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int indicator_right_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_right_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backselector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_gv_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_bluegray_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_orangegray_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_redgray_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_whitegray_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int callcustomphone_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int checkboxselector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int circle_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int circle_selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int default_ptr_flip = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int default_ptr_rotate = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int edit_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edit_nomal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int edit_selector = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int guider1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int guider2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int guider3 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int guider4 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int guiderdot_selector = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int headImagedefault = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int home_tab_personal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int home_tab_personal_selected = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_action_applyGuardian = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_action_back = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_bindingGuardian = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_more = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_basicInformation = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_launch = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_login_eye_normal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_login_eye_selected = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_login_password = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_login_rememberPassword_normal = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_login_rememberPassword_selected = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_login_username = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_map = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_medicalHistory = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_menu_alarm_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_menu_alarm_selected = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_menu_guardian_normal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_menu_guardian_selected = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_menu_health_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_menu_health_selected = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_menu_mine_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_menu_mine_selected = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_myInfo_advision_jianyi = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_myInfo_advision_qita = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_myInfo_advision_tousu = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_myInfo_advision_zixun = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_myInfomation_aboutUs = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_myInfomation_accountSecurity = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_myInfomation_advice = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_myInfomation_cacheRemover = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_myInfomation_call = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_myInfomation_message = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_myInfomation_personalData = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_myInfomation_phone = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_myInfomation_userName = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_myInfomation_versionDetection = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_register_combox_normal = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_register_combox_selected = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_register_eye_normal = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_register_eye_selected = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_register_message = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_register_password = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_register_phone = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_register_username = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_sex_man = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_sex_woman = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int Icon = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int icon_admin = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int icon_bankcard = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int icon_dailyPay = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int icon_ele = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int icon_fix = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int icon_gas = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int icon_housekeep = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int icon_housekeep_clean = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int icon_housekeep_cook = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int icon_housekeep_deal = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int icon_housekeep_moon = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int icon_housekeep_schoolrun = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int icon_housekeep_wash = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int icon_more = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int icon_nurse = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int icon_oil = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int icon_phone = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int icon_recharge = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int icon_record = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int icon_run = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int icon_traffic = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int icon_tv = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int icon_water = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int icon_withdraw = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int indicator_arrow = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int indicator_bg_bottom = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int indicator_bg_top = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int JT = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int login_bg = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int menu_bg = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int myInfomation_bgImage = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int myInfomation_headImage = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int myInfomation_next_arrow = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int myInfomation_setup_aboutus_logo = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int progress_1 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int progress_2 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int progress_3 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int progress_4 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int progress_5 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int progress_6 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int progress_7 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int progress_8 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int progress_bg_holo_light = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int progress_horizontal_holo_light = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int progress_horizontal_holo_light_right = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int progress_indeterminate_horizontal_holo = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int progress_primary_holo_light = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int progress_secondary_holo_light = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int progressbar_indeterminate_holo1 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int progressbar_indeterminate_holo2 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int progressbar_indeterminate_holo3 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int progressbar_indeterminate_holo4 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int progressbar_indeterminate_holo5 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int progressbar_indeterminate_holo6 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int progressbar_indeterminate_holo7 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int progressbar_indeterminate_holo8 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int radiobutton_noneSelected = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int radiobutton_selected = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int radiobutton_selector = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int registerAgreeTextSelector = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int regitercheckboxselector = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int relativeLayout_selector = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int setting = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int setting_selector = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int shape = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int splash = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int textselector = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int tv_guardiandetailselector = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int unbindselector = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int uparrow = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int user_center_camera = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int user_center_default = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int user_center_fav = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int user_center_integral = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int user_center_service = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int user_center_share = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int user_center_support = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int user_center_vip = 2130837653;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070159
			public const int Physical_Scroll = 2131165529;
			
			// aapt resource value: 0x7f070040
			public const int adviceViewPager = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int advicelistitemview = 2131165249;
			
			// aapt resource value: 0x7f070055
			public const int alarmHandleDetailInfoListitemView = 2131165269;
			
			// aapt resource value: 0x7f070059
			public const int alarmlistitemview = 2131165273;
			
			// aapt resource value: 0x7f070065
			public const int bankitemview = 2131165285;
			
			// aapt resource value: 0x7f07005e
			public const int bmap_view = 2131165278;
			
			// aapt resource value: 0x7f070003
			public const int both = 2131165187;
			
			// aapt resource value: 0x7f0700e3
			public const int btn_Action = 2131165411;
			
			// aapt resource value: 0x7f070029
			public const int btn_Add = 2131165225;
			
			// aapt resource value: 0x7f07007c
			public const int btn_Confirm = 2131165308;
			
			// aapt resource value: 0x7f0701c2
			public const int btn_Exit = 2131165634;
			
			// aapt resource value: 0x7f070101
			public const int btn_Login = 2131165441;
			
			// aapt resource value: 0x7f07001e
			public const int btn_Next = 2131165214;
			
			// aapt resource value: 0x7f0701d1
			public const int btn_Publish = 2131165649;
			
			// aapt resource value: 0x7f070196
			public const int btn_RegistNext = 2131165590;
			
			// aapt resource value: 0x7f070134
			public const int btn_Save = 2131165492;
			
			// aapt resource value: 0x7f070026
			public const int btn_Send = 2131165222;
			
			// aapt resource value: 0x7f07019b
			public const int btn_Submit = 2131165595;
			
			// aapt resource value: 0x7f0700d2
			public const int btn_action_agree = 2131165394;
			
			// aapt resource value: 0x7f0700d3
			public const int btn_action_disagree = 2131165395;
			
			// aapt resource value: 0x7f0701a9
			public const int btn_all = 2131165609;
			
			// aapt resource value: 0x7f070090
			public const int btn_cancel = 2131165328;
			
			// aapt resource value: 0x7f070079
			public const int btn_charge = 2131165305;
			
			// aapt resource value: 0x7f070088
			public const int btn_confirm = 2131165320;
			
			// aapt resource value: 0x7f0701ac
			public const int btn_done = 2131165612;
			
			// aapt resource value: 0x7f0700fa
			public const int btn_edit = 2131165434;
			
			// aapt resource value: 0x7f070084
			public const int btn_month = 2131165316;
			
			// aapt resource value: 0x7f070063
			public const int btn_other_search = 2131165283;
			
			// aapt resource value: 0x7f0700ea
			public const int btn_pic_cancel = 2131165418;
			
			// aapt resource value: 0x7f0700e9
			public const int btn_pick_photo = 2131165417;
			
			// aapt resource value: 0x7f0701b1
			public const int btn_search = 2131165617;
			
			// aapt resource value: 0x7f0700e6
			public const int btn_skip = 2131165414;
			
			// aapt resource value: 0x7f0700e7
			public const int btn_start_use = 2131165415;
			
			// aapt resource value: 0x7f0701ab
			public const int btn_sucessorder = 2131165611;
			
			// aapt resource value: 0x7f070070
			public const int btn_tab_bottom_finance = 2131165296;
			
			// aapt resource value: 0x7f070073
			public const int btn_tab_bottom_my = 2131165299;
			
			// aapt resource value: 0x7f07006d
			public const int btn_tab_bottom_server = 2131165293;
			
			// aapt resource value: 0x7f0700e8
			public const int btn_take_photo = 2131165416;
			
			// aapt resource value: 0x7f070085
			public const int btn_threemonth = 2131165317;
			
			// aapt resource value: 0x7f070082
			public const int btn_today = 2131165314;
			
			// aapt resource value: 0x7f0701aa
			public const int btn_todo = 2131165610;
			
			// aapt resource value: 0x7f070083
			public const int btn_week = 2131165315;
			
			// aapt resource value: 0x7f070197
			public const int cb_Agree = 2131165591;
			
			// aapt resource value: 0x7f070100
			public const int cb_Password = 2131165440;
			
			// aapt resource value: 0x7f070024
			public const int cb_defaut_bank = 2131165220;
			
			// aapt resource value: 0x7f070089
			public const int datepicker = 2131165321;
			
			// aapt resource value: 0x7f0700b8
			public const int dealAccountName = 2131165368;
			
			// aapt resource value: 0x7f0700b7
			public const int dealAmmount = 2131165367;
			
			// aapt resource value: 0x7f0700b0
			public const int dealRecordlistitemview = 2131165360;
			
			// aapt resource value: 0x7f0700b9
			public const int dealStatusDesc = 2131165369;
			
			// aapt resource value: 0x7f0700b5
			public const int dealTime = 2131165365;
			
			// aapt resource value: 0x7f0700b6
			public const int dealTypeDesc = 2131165366;
			
			// aapt resource value: 0x7f070004
			public const int disabled = 2131165188;
			
			// aapt resource value: 0x7f0700e5
			public const int dotImageLayout = 2131165413;
			
			// aapt resource value: 0x7f070027
			public const int edit_Code = 2131165223;
			
			// aapt resource value: 0x7f0701b7
			public const int edit_ConfirmPwd = 2131165623;
			
			// aapt resource value: 0x7f07001d
			public const int edit_IdCardNo = 2131165213;
			
			// aapt resource value: 0x7f0700fe
			public const int edit_PassWord = 2131165438;
			
			// aapt resource value: 0x7f070195
			public const int edit_Phone = 2131165589;
			
			// aapt resource value: 0x7f0701b5
			public const int edit_Pwd = 2131165621;
			
			// aapt resource value: 0x7f070193
			public const int edit_ReisterConfirmPwd = 2131165587;
			
			// aapt resource value: 0x7f070190
			public const int edit_ReisterNickName = 2131165584;
			
			// aapt resource value: 0x7f070191
			public const int edit_ReisterPwd = 2131165585;
			
			// aapt resource value: 0x7f07019a
			public const int edit_SecurityCode = 2131165594;
			
			// aapt resource value: 0x7f0700fc
			public const int edit_UserName = 2131165436;
			
			// aapt resource value: 0x7f07007b
			public const int edit_YDay = 2131165307;
			
			// aapt resource value: 0x7f07007a
			public const int edit_YHour = 2131165306;
			
			// aapt resource value: 0x7f0701d0
			public const int edit_advice_content = 2131165648;
			
			// aapt resource value: 0x7f0701cf
			public const int edit_advice_title = 2131165647;
			
			// aapt resource value: 0x7f070023
			public const int edit_bankCardNo = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int edit_bankbranch = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int edit_bankopenloc = 2131165217;
			
			// aapt resource value: 0x7f070133
			public const int edit_birth = 2131165491;
			
			// aapt resource value: 0x7f07001c
			public const int edit_cardOwnerName = 2131165212;
			
			// aapt resource value: 0x7f070078
			public const int edit_chargeAmmount = 2131165304;
			
			// aapt resource value: 0x7f0701cc
			public const int edit_dealPwd = 2131165644;
			
			// aapt resource value: 0x7f070081
			public const int edit_deal_endTime = 2131165313;
			
			// aapt resource value: 0x7f07007f
			public const int edit_deal_startTime = 2131165311;
			
			// aapt resource value: 0x7f070135
			public const int edit_email = 2131165493;
			
			// aapt resource value: 0x7f0701a2
			public const int edit_endServiceArea = 2131165602;
			
			// aapt resource value: 0x7f0701b0
			public const int edit_endTime = 2131165616;
			
			// aapt resource value: 0x7f070137
			public const int edit_fixedPhoneLast = 2131165495;
			
			// aapt resource value: 0x7f070136
			public const int edit_fixedphonePre = 2131165494;
			
			// aapt resource value: 0x7f07013b
			public const int edit_idCardLocation = 2131165499;
			
			// aapt resource value: 0x7f070157
			public const int edit_locationdeatil = 2131165527;
			
			// aapt resource value: 0x7f070156
			public const int edit_locationthreelevel = 2131165526;
			
			// aapt resource value: 0x7f0701ae
			public const int edit_orderName = 2131165614;
			
			// aapt resource value: 0x7f0701ad
			public const int edit_orderNo = 2131165613;
			
			// aapt resource value: 0x7f070060
			public const int edit_other_endTime = 2131165280;
			
			// aapt resource value: 0x7f0700ee
			public const int edit_other_searchTime = 2131165422;
			
			// aapt resource value: 0x7f07005f
			public const int edit_other_startTime = 2131165279;
			
			// aapt resource value: 0x7f070025
			public const int edit_prePhoneNo = 2131165221;
			
			// aapt resource value: 0x7f0701ce
			public const int edit_securityCode = 2131165646;
			
			// aapt resource value: 0x7f0701a3
			public const int edit_serviceDesc = 2131165603;
			
			// aapt resource value: 0x7f0701a1
			public const int edit_startServiceArea = 2131165601;
			
			// aapt resource value: 0x7f0701af
			public const int edit_startTime = 2131165615;
			
			// aapt resource value: 0x7f070158
			public const int edit_trueName = 2131165528;
			
			// aapt resource value: 0x7f0701ca
			public const int edit_withdrawmoney = 2131165642;
			
			// aapt resource value: 0x7f070180
			public const int fl_inner = 2131165568;
			
			// aapt resource value: 0x7f07017d
			public const int fl_inner_for_google_style = 2131165565;
			
			// aapt resource value: 0x7f0700ca
			public const int getApplyInfoListItemView = 2131165386;
			
			// aapt resource value: 0x7f070005
			public const int google = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int gridview = 2131165184;
			
			// aapt resource value: 0x7f0700cb
			public const int guardian_img_head = 2131165387;
			
			// aapt resource value: 0x7f0700e0
			public const int guardianlistitemview = 2131165408;
			
			// aapt resource value: 0x7f0700e4
			public const int guiderviewpager = 2131165412;
			
			// aapt resource value: 0x7f07012f
			public const int gv_server = 2131165487;
			
			// aapt resource value: 0x7f0700eb
			public const int healthitemview = 2131165419;
			
			// aapt resource value: 0x7f0700f4
			public const int housekeepservicelistitemView = 2131165428;
			
			// aapt resource value: 0x7f070104
			public const int id_mainContent = 2131165444;
			
			// aapt resource value: 0x7f070095
			public const int id_tv_loadingmsg = 2131165333;
			
			// aapt resource value: 0x7f07015b
			public const int img_BMI_Arraw = 2131165531;
			
			// aapt resource value: 0x7f07015c
			public const int img_BloodGlucose_Arraw = 2131165532;
			
			// aapt resource value: 0x7f07016e
			public const int img_BloodLipidParaFour_Arraw = 2131165550;
			
			// aapt resource value: 0x7f070168
			public const int img_BloodLipidParaOne_Arraw = 2131165544;
			
			// aapt resource value: 0x7f07016c
			public const int img_BloodLipidParaThree_Arraw = 2131165548;
			
			// aapt resource value: 0x7f07016a
			public const int img_BloodLipidParaTwo_Arraw = 2131165546;
			
			// aapt resource value: 0x7f07015e
			public const int img_BloodOxygenParaOne_Arraw = 2131165534;
			
			// aapt resource value: 0x7f070166
			public const int img_BodyTemperature_Arraw = 2131165542;
			
			// aapt resource value: 0x7f070164
			public const int img_BreathCapacity_Arraw = 2131165540;
			
			// aapt resource value: 0x7f070113
			public const int img_DealRecords = 2131165459;
			
			// aapt resource value: 0x7f070162
			public const int img_HeartRate_Arraw = 2131165538;
			
			// aapt resource value: 0x7f070151
			public const int img_IdCardLocation_arraw = 2131165521;
			
			// aapt resource value: 0x7f070141
			public const int img_IdCardNo_arraw = 2131165505;
			
			// aapt resource value: 0x7f070154
			public const int img_TrueLocation_arraw = 2131165524;
			
			// aapt resource value: 0x7f070170
			public const int img_UrineRoutinePH_Arraw = 2131165552;
			
			// aapt resource value: 0x7f070172
			public const int img_UrineRoutineSG_Arraw = 2131165554;
			
			// aapt resource value: 0x7f070174
			public const int img_UrineRoutineURO_Arraw = 2131165556;
			
			// aapt resource value: 0x7f0701ba
			public const int img_aboutUs = 2131165626;
			
			// aapt resource value: 0x7f070126
			public const int img_accountSecurity_arraw = 2131165478;
			
			// aapt resource value: 0x7f070042
			public const int img_adviceType = 2131165250;
			
			// aapt resource value: 0x7f07012c
			public const int img_advice_arraw = 2131165484;
			
			// aapt resource value: 0x7f070066
			public const int img_bank = 2131165286;
			
			// aapt resource value: 0x7f070110
			public const int img_bankCards = 2131165456;
			
			// aapt resource value: 0x7f07002c
			public const int img_basic_arraw = 2131165228;
			
			// aapt resource value: 0x7f070146
			public const int img_birth_arraw = 2131165510;
			
			// aapt resource value: 0x7f0701bf
			public const int img_cacheRemover = 2131165631;
			
			// aapt resource value: 0x7f0701c0
			public const int img_cacheRemover_arraw = 2131165632;
			
			// aapt resource value: 0x7f07012e
			public const int img_callCustom = 2131165486;
			
			// aapt resource value: 0x7f070129
			public const int img_certificate_arraw = 2131165481;
			
			// aapt resource value: 0x7f07010a
			public const int img_charge = 2131165450;
			
			// aapt resource value: 0x7f07009f
			public const int img_chargeEle = 2131165343;
			
			// aapt resource value: 0x7f0700a8
			public const int img_chargeFix = 2131165352;
			
			// aapt resource value: 0x7f0700a2
			public const int img_chargeGas = 2131165346;
			
			// aapt resource value: 0x7f0700ab
			public const int img_chargeOil = 2131165355;
			
			// aapt resource value: 0x7f070099
			public const int img_chargePhone = 2131165337;
			
			// aapt resource value: 0x7f0700ae
			public const int img_chargeTraffic = 2131165358;
			
			// aapt resource value: 0x7f0700a5
			public const int img_chargeTv = 2131165349;
			
			// aapt resource value: 0x7f07009c
			public const int img_chargeWater = 2131165340;
			
			// aapt resource value: 0x7f070020
			public const int img_choosebank = 2131165216;
			
			// aapt resource value: 0x7f070116
			public const int img_dailyPay = 2131165462;
			
			// aapt resource value: 0x7f07014e
			public const int img_email_arraw = 2131165518;
			
			// aapt resource value: 0x7f0700ff
			public const int img_eye = 2131165439;
			
			// aapt resource value: 0x7f0701b8
			public const int img_eye_ConfirmPwd = 2131165624;
			
			// aapt resource value: 0x7f0701b6
			public const int img_eye_Pwd = 2131165622;
			
			// aapt resource value: 0x7f070194
			public const int img_eye_ReisterConfirmPwd = 2131165588;
			
			// aapt resource value: 0x7f070192
			public const int img_eye_ReisterPwd = 2131165586;
			
			// aapt resource value: 0x7f07014b
			public const int img_fixedPhone_arraw = 2131165515;
			
			// aapt resource value: 0x7f070144
			public const int img_gender_arraw = 2131165508;
			
			// aapt resource value: 0x7f07011e
			public const int img_head = 2131165470;
			
			// aapt resource value: 0x7f07008b
			public const int img_header_back = 2131165323;
			
			// aapt resource value: 0x7f07001a
			public const int img_identity_arraw = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int img_loginPwd_arraw = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int img_payPwd_arraw = 2131165202;
			
			// aapt resource value: 0x7f070125
			public const int img_person_accountSecurity = 2131165477;
			
			// aapt resource value: 0x7f07012b
			public const int img_person_advice = 2131165483;
			
			// aapt resource value: 0x7f07002b
			public const int img_person_basic = 2131165227;
			
			// aapt resource value: 0x7f070128
			public const int img_person_certificate = 2131165480;
			
			// aapt resource value: 0x7f070016
			public const int img_phoneBind_arraw = 2131165206;
			
			// aapt resource value: 0x7f070149
			public const int img_phoneNumber_arraw = 2131165513;
			
			// aapt resource value: 0x7f070119
			public const int img_respect = 2131165465;
			
			// aapt resource value: 0x7f0701c6
			public const int img_rl_withdrawbank_arraw = 2131165638;
			
			// aapt resource value: 0x7f07019d
			public const int img_server = 2131165597;
			
			// aapt resource value: 0x7f0700f5
			public const int img_service = 2131165429;
			
			// aapt resource value: 0x7f07011c
			public const int img_setting = 2131165468;
			
			// aapt resource value: 0x7f0700cf
			public const int img_sex = 2131165391;
			
			// aapt resource value: 0x7f07013f
			public const int img_trueName_arraw = 2131165503;
			
			// aapt resource value: 0x7f0701bc
			public const int img_versionCheck = 2131165628;
			
			// aapt resource value: 0x7f0701bd
			public const int img_versionCheck_arraw = 2131165629;
			
			// aapt resource value: 0x7f07010d
			public const int img_withDraw = 2131165453;
			
			// aapt resource value: 0x7f07003f
			public const int iv_bottom_line = 2131165247;
			
			// aapt resource value: 0x7f0700cc
			public const int linearText = 2131165388;
			
			// aapt resource value: 0x7f070069
			public const int ll_BindGuardian = 2131165289;
			
			// aapt resource value: 0x7f0700d1
			public const int ll_action = 2131165393;
			
			// aapt resource value: 0x7f070122
			public const int ll_login_register = 2131165474;
			
			// aapt resource value: 0x7f070048
			public const int ll_maplocation = 2131165256;
			
			// aapt resource value: 0x7f07011b
			public const int ll_person = 2131165467;
			
			// aapt resource value: 0x7f07018f
			public const int ll_register = 2131165583;
			
			// aapt resource value: 0x7f07006f
			public const int ll_tab_bottom_finance = 2131165295;
			
			// aapt resource value: 0x7f070072
			public const int ll_tab_bottom_my = 2131165298;
			
			// aapt resource value: 0x7f07006c
			public const int ll_tab_bottom_server = 2131165292;
			
			// aapt resource value: 0x7f07011f
			public const int ll_userInfo = 2131165471;
			
			// aapt resource value: 0x7f070094
			public const int loadingImageView = 2131165332;
			
			// aapt resource value: 0x7f07007d
			public const int lv_bankType = 2131165309;
			
			// aapt resource value: 0x7f070068
			public const int lv_bankcard = 2131165288;
			
			// aapt resource value: 0x7f0700ba
			public const int lv_dealRecords = 2131165370;
			
			// aapt resource value: 0x7f0700d4
			public const int lv_guardianApply = 2131165396;
			
			// aapt resource value: 0x7f070054
			public const int lv_handleDetail = 2131165268;
			
			// aapt resource value: 0x7f0700f3
			public const int lv_housekeepservice = 2131165427;
			
			// aapt resource value: 0x7f07006a
			public const int lv_myGuardian = 2131165290;
			
			// aapt resource value: 0x7f0701b2
			public const int lv_ordersearch = 2131165618;
			
			// aapt resource value: 0x7f070064
			public const int lv_otherAlarm = 2131165284;
			
			// aapt resource value: 0x7f0700ef
			public const int lv_otherHealth = 2131165423;
			
			// aapt resource value: 0x7f07018e
			public const int lv_recordAdvice = 2131165582;
			
			// aapt resource value: 0x7f07006b
			public const int ly_main_tab_bottom = 2131165291;
			
			// aapt resource value: 0x7f070006
			public const int manualOnly = 2131165190;
			
			// aapt resource value: 0x7f070093
			public const int msgContent = 2131165331;
			
			// aapt resource value: 0x7f070091
			public const int msgIcon = 2131165329;
			
			// aapt resource value: 0x7f070092
			public const int msgTitle = 2131165330;
			
			// aapt resource value: 0x7f07017c
			public const int progressbar = 2131165564;
			
			// aapt resource value: 0x7f070007
			public const int pullDownFromTop = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int pullFromEnd = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int pullFromStart = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int pullUpFromBottom = 2131165194;
			
			// aapt resource value: 0x7f070105
			public const int pull_refresh_scroll_finance = 2131165445;
			
			// aapt resource value: 0x7f07011d
			public const int pull_refresh_scroll_my = 2131165469;
			
			// aapt resource value: 0x7f070181
			public const int pull_to_refresh_image = 2131165569;
			
			// aapt resource value: 0x7f070182
			public const int pull_to_refresh_progress = 2131165570;
			
			// aapt resource value: 0x7f07017f
			public const int pull_to_refresh_sub_text = 2131165567;
			
			// aapt resource value: 0x7f07017e
			public const int pull_to_refresh_text = 2131165566;
			
			// aapt resource value: 0x7f070185
			public const int pulling_left_progressbar = 2131165573;
			
			// aapt resource value: 0x7f070183
			public const int pulling_progress = 2131165571;
			
			// aapt resource value: 0x7f070186
			public const int pulling_right_progressbar = 2131165574;
			
			// aapt resource value: 0x7f070138
			public const int radioGroup = 2131165496;
			
			// aapt resource value: 0x7f070187
			public const int radio_advice_Group = 2131165575;
			
			// aapt resource value: 0x7f070188
			public const int rbtn_all = 2131165576;
			
			// aapt resource value: 0x7f07013a
			public const int rbtn_female = 2131165498;
			
			// aapt resource value: 0x7f07018a
			public const int rbtn_jianyi = 2131165578;
			
			// aapt resource value: 0x7f0701c8
			public const int rbtn_lesshour = 2131165640;
			
			// aapt resource value: 0x7f070139
			public const int rbtn_male = 2131165497;
			
			// aapt resource value: 0x7f0701c7
			public const int rbtn_moreday = 2131165639;
			
			// aapt resource value: 0x7f07018c
			public const int rbtn_other = 2131165580;
			
			// aapt resource value: 0x7f07018b
			public const int rbtn_tousu = 2131165579;
			
			// aapt resource value: 0x7f070189
			public const int rbtn_zixun = 2131165577;
			
			// aapt resource value: 0x7f070184
			public const int refreshing_progress = 2131165572;
			
			// aapt resource value: 0x7f070112
			public const int rl_DealRecords = 2131165458;
			
			// aapt resource value: 0x7f0700fd
			public const int rl_PassWord = 2131165437;
			
			// aapt resource value: 0x7f0700fb
			public const int rl_UserName = 2131165435;
			
			// aapt resource value: 0x7f0701b9
			public const int rl_aboutUs = 2131165625;
			
			// aapt resource value: 0x7f07002a
			public const int rl_admin_Set = 2131165226;
			
			// aapt resource value: 0x7f07002f
			public const int rl_admin_alarmRecords = 2131165231;
			
			// aapt resource value: 0x7f07002d
			public const int rl_admin_guardianApply = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int rl_admin_guardians = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int rl_admin_healthRecords = 2131165232;
			
			// aapt resource value: 0x7f07010f
			public const int rl_bankCards = 2131165455;
			
			// aapt resource value: 0x7f0701be
			public const int rl_cacheRemover = 2131165630;
			
			// aapt resource value: 0x7f070109
			public const int rl_charge = 2131165449;
			
			// aapt resource value: 0x7f07009e
			public const int rl_chargeEle = 2131165342;
			
			// aapt resource value: 0x7f0700a7
			public const int rl_chargeFix = 2131165351;
			
			// aapt resource value: 0x7f0700a1
			public const int rl_chargeGas = 2131165345;
			
			// aapt resource value: 0x7f0700aa
			public const int rl_chargeOil = 2131165354;
			
			// aapt resource value: 0x7f070098
			public const int rl_chargePhone = 2131165336;
			
			// aapt resource value: 0x7f0700ad
			public const int rl_chargeTraffic = 2131165357;
			
			// aapt resource value: 0x7f0700a4
			public const int rl_chargeTv = 2131165348;
			
			// aapt resource value: 0x7f07009b
			public const int rl_chargeWater = 2131165339;
			
			// aapt resource value: 0x7f070115
			public const int rl_dailyPay = 2131165461;
			
			// aapt resource value: 0x7f0700c7
			public const int rl_errand_Set = 2131165383;
			
			// aapt resource value: 0x7f0700c9
			public const int rl_errand_ordersearch = 2131165385;
			
			// aapt resource value: 0x7f0700c8
			public const int rl_errand_servicetype = 2131165384;
			
			// aapt resource value: 0x7f0700f0
			public const int rl_housekeep_Set = 2131165424;
			
			// aapt resource value: 0x7f0700f2
			public const int rl_housekeep_ordersearch = 2131165426;
			
			// aapt resource value: 0x7f0700f1
			public const int rl_housekeep_servicetype = 2131165425;
			
			// aapt resource value: 0x7f070130
			public const int rl_nurse_Set = 2131165488;
			
			// aapt resource value: 0x7f070132
			public const int rl_nurse_ordersearch = 2131165490;
			
			// aapt resource value: 0x7f070131
			public const int rl_nurse_servicetype = 2131165489;
			
			// aapt resource value: 0x7f070145
			public const int rl_person_Birth = 2131165509;
			
			// aapt resource value: 0x7f070143
			public const int rl_person_Gender = 2131165507;
			
			// aapt resource value: 0x7f070150
			public const int rl_person_IdCardLocation = 2131165520;
			
			// aapt resource value: 0x7f070140
			public const int rl_person_IdCardNo = 2131165504;
			
			// aapt resource value: 0x7f07013e
			public const int rl_person_TrueName = 2131165502;
			
			// aapt resource value: 0x7f07013c
			public const int rl_person_UserName = 2131165500;
			
			// aapt resource value: 0x7f070124
			public const int rl_person_accountSecurity = 2131165476;
			
			// aapt resource value: 0x7f07012a
			public const int rl_person_advice = 2131165482;
			
			// aapt resource value: 0x7f070123
			public const int rl_person_basic = 2131165475;
			
			// aapt resource value: 0x7f070127
			public const int rl_person_certificate = 2131165479;
			
			// aapt resource value: 0x7f07014d
			public const int rl_person_email = 2131165517;
			
			// aapt resource value: 0x7f07014a
			public const int rl_person_fixedPhone = 2131165514;
			
			// aapt resource value: 0x7f070018
			public const int rl_person_identity = 2131165208;
			
			// aapt resource value: 0x7f07000c
			public const int rl_person_loginPwd = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int rl_person_payPwd = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int rl_person_phoneBind = 2131165204;
			
			// aapt resource value: 0x7f070148
			public const int rl_person_phoneNumber = 2131165512;
			
			// aapt resource value: 0x7f070153
			public const int rl_person_trueLocation = 2131165523;
			
			// aapt resource value: 0x7f070118
			public const int rl_respect = 2131165464;
			
			// aapt resource value: 0x7f070034
			public const int rl_service_Area = 2131165236;
			
			// aapt resource value: 0x7f07003a
			public const int rl_service_chargingSet = 2131165242;
			
			// aapt resource value: 0x7f070037
			public const int rl_service_desc = 2131165239;
			
			// aapt resource value: 0x7f070031
			public const int rl_service_time = 2131165233;
			
			// aapt resource value: 0x7f0701bb
			public const int rl_versionCheck = 2131165627;
			
			// aapt resource value: 0x7f07010c
			public const int rl_withDraw = 2131165452;
			
			// aapt resource value: 0x7f0701c4
			public const int rl_withdraw_bank = 2131165636;
			
			// aapt resource value: 0x7f070046
			public const int scrollView1 = 2131165254;
			
			// aapt resource value: 0x7f070002
			public const int scrollview = 2131165186;
			
			// aapt resource value: 0x7f07019c
			public const int serveritemview = 2131165596;
			
			// aapt resource value: 0x7f0701a0
			public const int serviceAlllistitemView = 2131165600;
			
			// aapt resource value: 0x7f0701a4
			public const int serviceorderlistitemview = 2131165604;
			
			// aapt resource value: 0x7f070061
			public const int sp_alarmType = 2131165281;
			
			// aapt resource value: 0x7f070086
			public const int sp_deal_status = 2131165318;
			
			// aapt resource value: 0x7f070087
			public const int sp_deal_type = 2131165319;
			
			// aapt resource value: 0x7f0701b4
			public const int sp_endWeek = 2131165620;
			
			// aapt resource value: 0x7f070062
			public const int sp_other_guardian = 2131165282;
			
			// aapt resource value: 0x7f0701b3
			public const int sp_startWeek = 2131165619;
			
			// aapt resource value: 0x7f07003e
			public const int tab_btn_recordAdvice = 2131165246;
			
			// aapt resource value: 0x7f07003d
			public const int tab_btn_writeAdvice = 2131165245;
			
			// aapt resource value: 0x7f07008a
			public const int timepicker = 2131165322;
			
			// aapt resource value: 0x7f07015a
			public const int tv_BMI = 2131165530;
			
			// aapt resource value: 0x7f070147
			public const int tv_Birth = 2131165511;
			
			// aapt resource value: 0x7f0700ed
			public const int tv_BloodGlucose = 2131165421;
			
			// aapt resource value: 0x7f07016d
			public const int tv_BloodLipidParaFour = 2131165549;
			
			// aapt resource value: 0x7f070167
			public const int tv_BloodLipidParaOne = 2131165543;
			
			// aapt resource value: 0x7f07016b
			public const int tv_BloodLipidParaThree = 2131165547;
			
			// aapt resource value: 0x7f070169
			public const int tv_BloodLipidParaTwo = 2131165545;
			
			// aapt resource value: 0x7f07015d
			public const int tv_BloodOxygenParaOne = 2131165533;
			
			// aapt resource value: 0x7f070160
			public const int tv_BloodPressureParaOne = 2131165536;
			
			// aapt resource value: 0x7f07015f
			public const int tv_BloodPressureParaTwo = 2131165535;
			
			// aapt resource value: 0x7f070165
			public const int tv_BodyTemperature = 2131165541;
			
			// aapt resource value: 0x7f070163
			public const int tv_BreathCapacity = 2131165539;
			
			// aapt resource value: 0x7f0700d7
			public const int tv_Brnl = 2131165399;
			
			// aapt resource value: 0x7f0701c1
			public const int tv_CacheSize = 2131165633;
			
			// aapt resource value: 0x7f07003c
			public const int tv_ChargingSet = 2131165244;
			
			// aapt resource value: 0x7f0700da
			public const int tv_ContactAddress = 2131165402;
			
			// aapt resource value: 0x7f070114
			public const int tv_DealRecords = 2131165460;
			
			// aapt resource value: 0x7f0700dc
			public const int tv_Email = 2131165404;
			
			// aapt resource value: 0x7f0700d6
			public const int tv_Gender = 2131165398;
			
			// aapt resource value: 0x7f0700ce
			public const int tv_GuardianStatus = 2131165390;
			
			// aapt resource value: 0x7f070161
			public const int tv_HeartRate = 2131165537;
			
			// aapt resource value: 0x7f0700dd
			public const int tv_Height = 2131165405;
			
			// aapt resource value: 0x7f0700df
			public const int tv_HereditaryDisease = 2131165407;
			
			// aapt resource value: 0x7f0700d9
			public const int tv_IDNumber = 2131165401;
			
			// aapt resource value: 0x7f070152
			public const int tv_IdCardLocation = 2131165522;
			
			// aapt resource value: 0x7f070142
			public const int tv_IdCardNo = 2131165506;
			
			// aapt resource value: 0x7f0700cd
			public const int tv_Name = 2131165389;
			
			// aapt resource value: 0x7f0701a6
			public const int tv_OrderAmmount = 2131165606;
			
			// aapt resource value: 0x7f0701a8
			public const int tv_OrderPlaces = 2131165608;
			
			// aapt resource value: 0x7f0701a5
			public const int tv_OrderSponsor = 2131165605;
			
			// aapt resource value: 0x7f0701a7
			public const int tv_OrderTime = 2131165607;
			
			// aapt resource value: 0x7f0700d8
			public const int tv_PhoneNumberOne = 2131165400;
			
			// aapt resource value: 0x7f070199
			public const int tv_PhoneShow = 2131165593;
			
			// aapt resource value: 0x7f070103
			public const int tv_Register = 2131165443;
			
			// aapt resource value: 0x7f070028
			public const int tv_SendCodeStatusShow = 2131165224;
			
			// aapt resource value: 0x7f0700db
			public const int tv_TelePhoneNumber = 2131165403;
			
			// aapt resource value: 0x7f0700ec
			public const int tv_TestTime = 2131165420;
			
			// aapt resource value: 0x7f070155
			public const int tv_TrueLocation = 2131165525;
			
			// aapt resource value: 0x7f0700d5
			public const int tv_TrueName = 2131165397;
			
			// aapt resource value: 0x7f070179
			public const int tv_UrineRoutineBIL = 2131165561;
			
			// aapt resource value: 0x7f070176
			public const int tv_UrineRoutineBLO = 2131165558;
			
			// aapt resource value: 0x7f070178
			public const int tv_UrineRoutineGLU = 2131165560;
			
			// aapt resource value: 0x7f070177
			public const int tv_UrineRoutineKET = 2131165559;
			
			// aapt resource value: 0x7f07016f
			public const int tv_UrineRoutinePH = 2131165551;
			
			// aapt resource value: 0x7f07017b
			public const int tv_UrineRoutineRBC = 2131165563;
			
			// aapt resource value: 0x7f07017a
			public const int tv_UrineRoutineRPO = 2131165562;
			
			// aapt resource value: 0x7f070171
			public const int tv_UrineRoutineSG = 2131165553;
			
			// aapt resource value: 0x7f070173
			public const int tv_UrineRoutineURO = 2131165555;
			
			// aapt resource value: 0x7f070175
			public const int tv_UrineRoutineWBC = 2131165557;
			
			// aapt resource value: 0x7f07013d
			public const int tv_UserName = 2131165501;
			
			// aapt resource value: 0x7f0700de
			public const int tv_Weight = 2131165406;
			
			// aapt resource value: 0x7f0700f9
			public const int tv_YDay = 2131165433;
			
			// aapt resource value: 0x7f0700f8
			public const int tv_YHour = 2131165432;
			
			// aapt resource value: 0x7f0701c3
			public const int tv_accountBalance = 2131165635;
			
			// aapt resource value: 0x7f07008e
			public const int tv_action = 2131165326;
			
			// aapt resource value: 0x7f070045
			public const int tv_adviceContent = 2131165253;
			
			// aapt resource value: 0x7f070044
			public const int tv_adviceTime = 2131165252;
			
			// aapt resource value: 0x7f070043
			public const int tv_adviceTitle = 2131165251;
			
			// aapt resource value: 0x7f07005d
			public const int tv_alarmContent = 2131165277;
			
			// aapt resource value: 0x7f07005c
			public const int tv_alarmStatus = 2131165276;
			
			// aapt resource value: 0x7f07005b
			public const int tv_alarmTime = 2131165275;
			
			// aapt resource value: 0x7f07005a
			public const int tv_alarmTrueName = 2131165274;
			
			// aapt resource value: 0x7f0700d0
			public const int tv_applyContent = 2131165392;
			
			// aapt resource value: 0x7f07000b
			public const int tv_appversion = 2131165195;
			
			// aapt resource value: 0x7f070107
			public const int tv_availableAssets = 2131165447;
			
			// aapt resource value: 0x7f07008c
			public const int tv_back = 2131165324;
			
			// aapt resource value: 0x7f070111
			public const int tv_bankCards = 2131165457;
			
			// aapt resource value: 0x7f070067
			public const int tv_bankNo = 2131165287;
			
			// aapt resource value: 0x7f07010b
			public const int tv_charge = 2131165451;
			
			// aapt resource value: 0x7f070076
			public const int tv_chargeAccount = 2131165302;
			
			// aapt resource value: 0x7f070075
			public const int tv_chargeAccountdesc = 2131165301;
			
			// aapt resource value: 0x7f070077
			public const int tv_chargeAmmount = 2131165303;
			
			// aapt resource value: 0x7f0700a0
			public const int tv_chargeEle = 2131165344;
			
			// aapt resource value: 0x7f0700a9
			public const int tv_chargeFix = 2131165353;
			
			// aapt resource value: 0x7f0700a3
			public const int tv_chargeGas = 2131165347;
			
			// aapt resource value: 0x7f0700ac
			public const int tv_chargeOil = 2131165356;
			
			// aapt resource value: 0x7f07009a
			public const int tv_chargePhone = 2131165338;
			
			// aapt resource value: 0x7f0700af
			public const int tv_chargeTraffic = 2131165359;
			
			// aapt resource value: 0x7f0700a6
			public const int tv_chargeTv = 2131165350;
			
			// aapt resource value: 0x7f07009d
			public const int tv_chargeWater = 2131165341;
			
			// aapt resource value: 0x7f07003b
			public const int tv_chargingSet_desc = 2131165243;
			
			// aapt resource value: 0x7f07001f
			public const int tv_choosebank = 2131165215;
			
			// aapt resource value: 0x7f07012d
			public const int tv_customPhone = 2131165485;
			
			// aapt resource value: 0x7f070117
			public const int tv_dailyPay = 2131165463;
			
			// aapt resource value: 0x7f0700c4
			public const int tv_dealAccount = 2131165380;
			
			// aapt resource value: 0x7f0700b3
			public const int tv_dealAccountName = 2131165363;
			
			// aapt resource value: 0x7f0700c3
			public const int tv_dealAccountNamedesc = 2131165379;
			
			// aapt resource value: 0x7f0700b2
			public const int tv_dealAmmount = 2131165362;
			
			// aapt resource value: 0x7f0700c0
			public const int tv_dealAmmountdesc = 2131165376;
			
			// aapt resource value: 0x7f0700be
			public const int tv_dealName = 2131165374;
			
			// aapt resource value: 0x7f0700bd
			public const int tv_dealNamedesc = 2131165373;
			
			// aapt resource value: 0x7f0700bc
			public const int tv_dealNo = 2131165372;
			
			// aapt resource value: 0x7f0700bb
			public const int tv_dealNodesc = 2131165371;
			
			// aapt resource value: 0x7f0701cb
			public const int tv_dealPwd = 2131165643;
			
			// aapt resource value: 0x7f0700c6
			public const int tv_dealRemark = 2131165382;
			
			// aapt resource value: 0x7f0700c5
			public const int tv_dealRemarkdesc = 2131165381;
			
			// aapt resource value: 0x7f0700b4
			public const int tv_dealStatusDesc = 2131165364;
			
			// aapt resource value: 0x7f07007e
			public const int tv_dealTime = 2131165310;
			
			// aapt resource value: 0x7f0700bf
			public const int tv_dealTimedesc = 2131165375;
			
			// aapt resource value: 0x7f0700c2
			public const int tv_dealType = 2131165378;
			
			// aapt resource value: 0x7f0700b1
			public const int tv_dealTypeDesc = 2131165361;
			
			// aapt resource value: 0x7f0700c1
			public const int tv_dealTypedesc = 2131165377;
			
			// aapt resource value: 0x7f07008d
			public const int tv_desc = 2131165325;
			
			// aapt resource value: 0x7f0700e2
			public const int tv_detail = 2131165410;
			
			// aapt resource value: 0x7f070047
			public const int tv_detail_alamTime = 2131165255;
			
			// aapt resource value: 0x7f07004b
			public const int tv_detail_alarmContent = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int tv_detail_alarmDeviceId = 2131165261;
			
			// aapt resource value: 0x7f070049
			public const int tv_detail_alarmPosition = 2131165257;
			
			// aapt resource value: 0x7f070050
			public const int tv_detail_alarmWay = 2131165264;
			
			// aapt resource value: 0x7f070052
			public const int tv_detail_cTrueName = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int tv_detail_cphoneNumberOne = 2131165267;
			
			// aapt resource value: 0x7f07004c
			public const int tv_detail_deviceElectricity = 2131165260;
			
			// aapt resource value: 0x7f070051
			public const int tv_detail_handleUserType = 2131165265;
			
			// aapt resource value: 0x7f07004e
			public const int tv_detail_remark = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int tv_detail_status = 2131165263;
			
			// aapt resource value: 0x7f07004a
			public const int tv_detail_trueName = 2131165258;
			
			// aapt resource value: 0x7f07014f
			public const int tv_email = 2131165519;
			
			// aapt resource value: 0x7f07014c
			public const int tv_fixedPhone = 2131165516;
			
			// aapt resource value: 0x7f070102
			public const int tv_forgetPwd = 2131165442;
			
			// aapt resource value: 0x7f070108
			public const int tv_frozenAssets = 2131165448;
			
			// aapt resource value: 0x7f070057
			public const int tv_handledetail_handleContent = 2131165271;
			
			// aapt resource value: 0x7f070056
			public const int tv_handledetail_handleTime = 2131165270;
			
			// aapt resource value: 0x7f070058
			public const int tv_handledetail_remark = 2131165272;
			
			// aapt resource value: 0x7f07001b
			public const int tv_identity = 2131165211;
			
			// aapt resource value: 0x7f070198
			public const int tv_linkServiceAgree = 2131165592;
			
			// aapt resource value: 0x7f0700e1
			public const int tv_location = 2131165409;
			
			// aapt resource value: 0x7f07000f
			public const int tv_loginPwd = 2131165199;
			
			// aapt resource value: 0x7f070097
			public const int tv_msgContent = 2131165335;
			
			// aapt resource value: 0x7f070120
			public const int tv_nickName = 2131165472;
			
			// aapt resource value: 0x7f070013
			public const int tv_payPwd = 2131165203;
			
			// aapt resource value: 0x7f070019
			public const int tv_person_identity = 2131165209;
			
			// aapt resource value: 0x7f07000d
			public const int tv_person_loginPwd = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int tv_person_payPwd = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int tv_person_phoneBind = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int tv_phoneBind = 2131165207;
			
			// aapt resource value: 0x7f07008f
			public const int tv_phoneNumber = 2131165327;
			
			// aapt resource value: 0x7f070121
			public const int tv_phonenumber = 2131165473;
			
			// aapt resource value: 0x7f07018d
			public const int tv_recordNum = 2131165581;
			
			// aapt resource value: 0x7f07011a
			public const int tv_respect = 2131165466;
			
			// aapt resource value: 0x7f0701cd
			public const int tv_securityCode = 2131165645;
			
			// aapt resource value: 0x7f07019e
			public const int tv_server = 2131165598;
			
			// aapt resource value: 0x7f070036
			public const int tv_serviceArea = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int tv_serviceAreaDesc = 2131165237;
			
			// aapt resource value: 0x7f0700f7
			public const int tv_serviceDesc = 2131165431;
			
			// aapt resource value: 0x7f0700f6
			public const int tv_serviceName = 2131165430;
			
			// aapt resource value: 0x7f070033
			public const int tv_serviceTime = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int tv_serviceTimeDesc = 2131165234;
			
			// aapt resource value: 0x7f07019f
			public const int tv_service_agree = 2131165599;
			
			// aapt resource value: 0x7f070038
			public const int tv_service_desc_desc = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int tv_servicedesc = 2131165241;
			
			// aapt resource value: 0x7f070080
			public const int tv_split = 2131165312;
			
			// aapt resource value: 0x7f070071
			public const int tv_tab_bottom_finance = 2131165297;
			
			// aapt resource value: 0x7f070074
			public const int tv_tab_bottom_my = 2131165300;
			
			// aapt resource value: 0x7f07006e
			public const int tv_tab_bottom_server = 2131165294;
			
			// aapt resource value: 0x7f070096
			public const int tv_title = 2131165334;
			
			// aapt resource value: 0x7f070106
			public const int tv_totalAssets = 2131165446;
			
			// aapt resource value: 0x7f07010e
			public const int tv_withDraw = 2131165454;
			
			// aapt resource value: 0x7f0701c5
			public const int tv_with_drawbank = 2131165637;
			
			// aapt resource value: 0x7f0701c9
			public const int tv_withdrawmoney = 2131165641;
			
			// aapt resource value: 0x7f070001
			public const int webview = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutUsLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountSecurityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddBankStepOneLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddBankStepTwoLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AdminMainLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AdminSetLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int AdviceLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int AdviceRecordListItemView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int AlarmDetailInfoLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int AlarmHandleDetailInfoListitemView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int alarmListitemView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int AlarmLocationLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int AlarmRecordsLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int BankCardlListitemView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int BankCardsLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int BindGuardianLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int bottom_bar = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int CertificateLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ChargeEleLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ChargeFixLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ChargeGasLayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ChargeLayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ChargeOilLayout = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ChargePhoneLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ChargeTrafficLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int ChargeTvLayout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ChargeWaterLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int ChargingSetLayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ChooseBankTypeLayout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int ChooseDealRecordsConditionLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ChooseWithDrawBankLayout = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int commondatepickerlayout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int commontimepickerlayout = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int custom_title_bar = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int customconfirmphonedialog = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int customer_notitfication_layout = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int customprogressdialog = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int customunbinddialogLayout = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int DailyPayLayout = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int DealRecordListitemView = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int DealRecordsLayout = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int DetailRecordDetailLayout = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int ErrandMainLayout = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int getApplyInfoListItemView = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int GuardianApplyLayout = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int GuardianDetailInfoLayout = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int guardianListitemView = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int Guider = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int Guider1 = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int Guider2 = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int Guider3 = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int Guider4 = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int headImgSelectorPop = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int healthListItemView = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int HealthRecordsLayout = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int HouseKeepMainLayout = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int HouseKeepServiceLayout = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int housekeepServiceListItemView = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int Login = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int Main = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int Main_Tab_Finance = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int Main_Tab_My = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int Main_Tab_Server = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int NurseMainLayout = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int NurseServiceLayout = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int PersonInfoBirthLayout = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int PersonInfoEmailLayout = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int PersonInfoFixedPhoneLayout = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int PersonInfoGenderLayout = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int PersonInfoIdCardNoLayout = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int PersonInfoIdCardNoLocationLayout = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int PersonInfoLayout = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int PersonInfoTrueLocationLayout = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int PersonInfoTrueNameLayout = 2130903113;
			
			// aapt resource value: 0x7f03004a
			public const int PhysicalDetailInfoLayout = 2130903114;
			
			// aapt resource value: 0x7f03004b
			public const int progressbar = 2130903115;
			
			// aapt resource value: 0x7f03004c
			public const int pull_to_refresh_header_google_style = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public const int pull_to_refresh_header_horizontal = 2130903117;
			
			// aapt resource value: 0x7f03004e
			public const int pull_to_refresh_header_vertical = 2130903118;
			
			// aapt resource value: 0x7f03004f
			public const int pull_to_refresh_progress_google_style = 2130903119;
			
			// aapt resource value: 0x7f030050
			public const int pulling_progress_layout = 2130903120;
			
			// aapt resource value: 0x7f030051
			public const int RecordAdviceLayout = 2130903121;
			
			// aapt resource value: 0x7f030052
			public const int RegisterStepOneLayout = 2130903122;
			
			// aapt resource value: 0x7f030053
			public const int RegisterStepTwoLayout = 2130903123;
			
			// aapt resource value: 0x7f030054
			public const int SendSecurityCodeLayout = 2130903124;
			
			// aapt resource value: 0x7f030055
			public const int ServerGridItemView = 2130903125;
			
			// aapt resource value: 0x7f030056
			public const int ServiceAgreeLayout = 2130903126;
			
			// aapt resource value: 0x7f030057
			public const int ServiceAllListitemView = 2130903127;
			
			// aapt resource value: 0x7f030058
			public const int ServiceAreaLayout = 2130903128;
			
			// aapt resource value: 0x7f030059
			public const int ServiceDescLayout = 2130903129;
			
			// aapt resource value: 0x7f03005a
			public const int ServiceOrderdetailLayout = 2130903130;
			
			// aapt resource value: 0x7f03005b
			public const int serviceOrderListItemView = 2130903131;
			
			// aapt resource value: 0x7f03005c
			public const int ServiceOrderSearchLayout = 2130903132;
			
			// aapt resource value: 0x7f03005d
			public const int ServiceTimeLayout = 2130903133;
			
			// aapt resource value: 0x7f03005e
			public const int SetPasswordLayout = 2130903134;
			
			// aapt resource value: 0x7f03005f
			public const int Setting = 2130903135;
			
			// aapt resource value: 0x7f030060
			public const int Splash = 2130903136;
			
			// aapt resource value: 0x7f030061
			public const int title_action_bar = 2130903137;
			
			// aapt resource value: 0x7f030062
			public const int WithDrawLayout = 2130903138;
			
			// aapt resource value: 0x7f030063
			public const int WriteAdviceLayout = 2130903139;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080016
			public const int Register = 2131230742;
			
			// aapt resource value: 0x7f080006
			public const int app_name = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int confirm = 2131230731;
			
			// aapt resource value: 0x7f080018
			public const int customphoneNumber = 2131230744;
			
			// aapt resource value: 0x7f08000c
			public const int edit = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int forgetPwd = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int loadMsg = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int loginMsg = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int newAcount = 2131230728;
			
			// aapt resource value: 0x7f080010
			public const int pullDownLbl = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int pullDownRefreshLbl = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int pullDownReleaseLbl = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int pullUpLbl = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int pullUpRefreshLbl = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int pullUpReleaseLbl = 2131230741;
			
			// aapt resource value: 0x7f080003
			public const int pull_to_refresh_from_bottom_pull_label = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int pull_to_refresh_from_bottom_refreshing_label = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int pull_to_refresh_from_bottom_release_label = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int pull_to_refresh_pull_label = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int pull_to_refresh_refreshing_label = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int pull_to_refresh_release_label = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int save = 2131230730;
			
			// aapt resource value: 0x7f080017
			public const int securityCode = 2131230743;
			
			// aapt resource value: 0x7f080007
			public const int serviceAgree = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int share = 2131230733;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0007
			public const int AnimationPreview = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int Animationbottom = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0003
			public const int CustomDialog = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int CustomProgressDialog = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int MyCustomTheme = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int TitleBarBackground = 2131361793;
			
			// aapt resource value: 0x7f0a0009
			public const int action_bar = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int action_bar_tv = 2131361802;
			
			// aapt resource value: 0x7f0a0005
			public const int bottom_tab_tv = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int btn_head_pop = 2131361798;
			
			// aapt resource value: 0x7f0a0015
			public const int edit_bank_value = 2131361813;
			
			// aapt resource value: 0x7f0a000e
			public const int personbasic_ll_layout = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int personbasic_tv_key = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int personbasic_value = 2131361808;
			
			// aapt resource value: 0x7f0a000d
			public const int pulltorefresh_lv = 2131361805;
			
			// aapt resource value: 0x7f0a0013
			public const int rl_bank_item = 2131361811;
			
			// aapt resource value: 0x7f0a000c
			public const int tab_btn_style = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int tab_linerlayout = 2131361803;
			
			// aapt resource value: 0x7f0a0014
			public const int tv_bank_key = 2131361812;
			
			// aapt resource value: 0x7f0a0011
			public const int tv_key = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int tv_value = 2131361810;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int pulltorefresh = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130772005,
					2130772006,
					2130772007,
					2130772008};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] PullToRefresh = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 34
			public const int PullToRefresh_ptrAdapterViewBackground = 34;
			
			// aapt resource value: 12
			public const int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public const int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 36
			public const int PullToRefresh_ptrDrawableBottom = 36;
			
			// aapt resource value: 8
			public const int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public const int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 35
			public const int PullToRefresh_ptrDrawableTop = 35;
			
			// aapt resource value: 19
			public const int PullToRefresh_ptrFriction = 19;
			
			// aapt resource value: 15
			public const int PullToRefresh_ptrGoogleProgressStyle = 15;
			
			// aapt resource value: 14
			public const int PullToRefresh_ptrGoogleViewStyle = 14;
			
			// aapt resource value: 1
			public const int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public const int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public const int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public const int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 30
			public const int PullToRefresh_ptrHideRefeshableViewWhileRefreshingDuration = 30;
			
			// aapt resource value: 27
			public const int PullToRefresh_ptrHideRefeshableViewWhileRefreshingEnabled = 27;
			
			// aapt resource value: 13
			public const int PullToRefresh_ptrIndicatorStyle = 13;
			
			// aapt resource value: 23
			public const int PullToRefresh_ptrListViewExtrasEnabled = 23;
			
			// aapt resource value: 4
			public const int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public const int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 16
			public const int PullToRefresh_ptrPullLabel = 16;
			
			// aapt resource value: 33
			public const int PullToRefresh_ptrRefeshableViewProgressBarOnCenterHeight = 33;
			
			// aapt resource value: 32
			public const int PullToRefresh_ptrRefeshableViewProgressBarOnCenterWidth = 32;
			
			// aapt resource value: 17
			public const int PullToRefresh_ptrRefreshLabel = 17;
			
			// aapt resource value: 0
			public const int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 18
			public const int PullToRefresh_ptrReleaseLabel = 18;
			
			// aapt resource value: 24
			public const int PullToRefresh_ptrRotateDrawableWhilePulling = 24;
			
			// aapt resource value: 22
			public const int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 22;
			
			// aapt resource value: 25
			public const int PullToRefresh_ptrSetGoogleViewLayoutSizeToActionbarHeight = 25;
			
			// aapt resource value: 29
			public const int PullToRefresh_ptrShowGoogleStyleViewAnimationDuration = 29;
			
			// aapt resource value: 26
			public const int PullToRefresh_ptrShowGoogleStyleViewAnimationEnabled = 26;
			
			// aapt resource value: 5
			public const int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 20
			public const int PullToRefresh_ptrSmoothScrollDuration = 20;
			
			// aapt resource value: 21
			public const int PullToRefresh_ptrSmoothScrollLongDuration = 21;
			
			// aapt resource value: 11
			public const int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			// aapt resource value: 31
			public const int PullToRefresh_ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingDuration = 31;
			
			// aapt resource value: 28
			public const int PullToRefresh_ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingEnabled = 28;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
